apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftp-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sftp
  persistentVolumeReclaimPolicy: Retain
