apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data
  namespace: utils-sftp
spec:
  volumeName: sftp-pv   # 👈 Bind explicitly
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
