apiVersion: v1
kind: Service
metadata:
  name: sftp
  namespace: utils-sftp
spec:
  selector:
    app: sftp
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
    - name: sftp
      port: 2022
      targetPort: 2022
      nodePort: 30022
      protocol: TCP
    - name: ftp
      port: 2121
      targetPort: 2121
      nodePort: 30021
      protocol: TCP
    - name: ftp-passive
      port: 50000
      targetPort: 50000
      nodePort: 30050
      protocol: TCP
    - name: webdav
      port: 10080
      targetPort: 10080
      nodePort: 30081
      protocol: TCP
