apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  namespace: utils-sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
      - name: sftp
        image: drakkan/sftpgo:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 2022
          name: sftp
        - containerPort: 2121
          name: ftp
        - containerPort: 10080
          name: webdav
        - containerPort: 50001
          name: p50001
          protocol: TCP
        - containerPort: 50002
          name: p50002
          protocol: TCP
        - containerPort: 50003
          name: p50003
          protocol: TCP
        - containerPort: 50004
          name: p50004
          protocol: TCP
        - containerPort: 50005
          name: p50005
          protocol: TCP
        - containerPort: 50006
          name: p50006
          protocol: TCP
        - containerPort: 50007
          name: p50007
          protocol: TCP
        - containerPort: 50008
          name: p50008
          protocol: TCP
        - containerPort: 50009
          name: p50009
          protocol: TCP
        - containerPort: 50010
          name: p50010
          protocol: TCP
        - containerPort: 50011
          name: p50011
          protocol: TCP
        - containerPort: 50012
          name: p50012
          protocol: TCP
        - containerPort: 50013
          name: p50013
          protocol: TCP
        - containerPort: 50014
          name: p50014
          protocol: TCP
        - containerPort: 50015
          name: p50015
          protocol: TCP
        - containerPort: 50016
          name: p50016
          protocol: TCP
        - containerPort: 50017
          name: p50017
          protocol: TCP
        - containerPort: 50018
          name: p50018
          protocol: TCP
        - containerPort: 50019
          name: p50019
          protocol: TCP
        - containerPort: 50020
          name: p50020
          protocol: TCP
        - containerPort: 50021
          name: p50021
          protocol: TCP
        - containerPort: 50022
          name: p50022
          protocol: TCP
        - containerPort: 50023
          name: p50023
          protocol: TCP
        - containerPort: 50024
          name: p50024
          protocol: TCP
        - containerPort: 50025
          name: p50025
          protocol: TCP
        - containerPort: 50026
          name: p50026
          protocol: TCP
        - containerPort: 50027
          name: p50027
          protocol: TCP
        - containerPort: 50028
          name: p50028
          protocol: TCP
        - containerPort: 50029
          name: p50029
          protocol: TCP
        - containerPort: 50030
          name: p50030
          protocol: TCP
        - containerPort: 50031
          name: p50031
          protocol: TCP
        - containerPort: 50032
          name: p50032
          protocol: TCP
        - containerPort: 50033
          name: p50033
          protocol: TCP
        - containerPort: 50034
          name: p50034
          protocol: TCP
        - containerPort: 50035
          name: p50035
          protocol: TCP
        - containerPort: 50036
          name: p50036
          protocol: TCP
        - containerPort: 50037
          name: p50037
          protocol: TCP
        - containerPort: 50038
          name: p50038
          protocol: TCP
        - containerPort: 50039
          name: p50039
          protocol: TCP
        - containerPort: 50040
          name: p50040
          protocol: TCP
        - containerPort: 50041
          name: p50041
          protocol: TCP
        - containerPort: 50042
          name: p50042
          protocol: TCP
        - containerPort: 50043
          name: p50043
          protocol: TCP
        - containerPort: 50044
          name: p50044
          protocol: TCP
        - containerPort: 50045
          name: p50045
          protocol: TCP
        - containerPort: 50046
          name: p50046
          protocol: TCP
        - containerPort: 50047
          name: p50047
          protocol: TCP
        - containerPort: 50048
          name: p50048
          protocol: TCP
        - containerPort: 50049
          name: p50049
          protocol: TCP
        - containerPort: 50050
          name: p50050
          protocol: TCP
        - containerPort: 50051
          name: p50051
          protocol: TCP
        - containerPort: 50052
          name: p50052
          protocol: TCP
        - containerPort: 50053
          name: p50053
          protocol: TCP
        - containerPort: 50054
          name: p50054
          protocol: TCP
        - containerPort: 50055
          name: p50055
          protocol: TCP
        - containerPort: 50056
          name: p50056
          protocol: TCP
        - containerPort: 50057
          name: p50057
          protocol: TCP
        - containerPort: 50058
          name: p50058
          protocol: TCP
        - containerPort: 50059
          name: p50059
          protocol: TCP
        - containerPort: 50060
          name: p50060
          protocol: TCP
        - containerPort: 50061
          name: p50061
          protocol: TCP
        - containerPort: 50062
          name: p50062
          protocol: TCP
        - containerPort: 50063
          name: p50063
          protocol: TCP
        - containerPort: 50064
          name: p50064
          protocol: TCP
        - containerPort: 50065
          name: p50065
          protocol: TCP
        - containerPort: 50066
          name: p50066
          protocol: TCP
        - containerPort: 50067
          name: p50067
          protocol: TCP
        - containerPort: 50068
          name: p50068
          protocol: TCP
        - containerPort: 50069
          name: p50069
          protocol: TCP
        - containerPort: 50070
          name: p50070
          protocol: TCP
        - containerPort: 50071
          name: p50071
          protocol: TCP
        - containerPort: 50072
          name: p50072
          protocol: TCP
        - containerPort: 50073
          name: p50073
          protocol: TCP
        - containerPort: 50074
          name: p50074
          protocol: TCP
        - containerPort: 50075
          name: p50075
          protocol: TCP
        - containerPort: 50076
          name: p50076
          protocol: TCP
        - containerPort: 50077
          name: p50077
          protocol: TCP
        - containerPort: 50078
          name: p50078
          protocol: TCP
        - containerPort: 50079
          name: p50079
          protocol: TCP
        - containerPort: 50080
          name: p50080
          protocol: TCP
        - containerPort: 50081
          name: p50081
          protocol: TCP
        - containerPort: 50082
          name: p50082
          protocol: TCP
        - containerPort: 50083
          name: p50083
          protocol: TCP
        - containerPort: 50084
          name: p50084
          protocol: TCP
        - containerPort: 50085
          name: p50085
          protocol: TCP
        - containerPort: 50086
          name: p50086
          protocol: TCP
        - containerPort: 50087
          name: p50087
          protocol: TCP
        - containerPort: 50088
          name: p50088
          protocol: TCP
        - containerPort: 50089
          name: p50089
          protocol: TCP
        - containerPort: 50090
          name: p50090
          protocol: TCP
        - containerPort: 50091
          name: p50091
          protocol: TCP
        - containerPort: 50092
          name: p50092
          protocol: TCP
        - containerPort: 50093
          name: p50093
          protocol: TCP
        - containerPort: 50094
          name: p50094
          protocol: TCP
        - containerPort: 50095
          name: p50095
          protocol: TCP
        - containerPort: 50096
          name: p50096
          protocol: TCP
        - containerPort: 50097
          name: p50097
          protocol: TCP
        - containerPort: 50098
          name: p50098
          protocol: TCP
        - containerPort: 50099
          name: p50099
          protocol: TCP
        - containerPort: 50100
          name: p50100
          protocol: TCP

        volumeMounts:
        - name: sftp-data
          mountPath: /srv/sftp/data
        env:
        - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
          value: "1"
        - name: SFTPGO_DEFAULT_ADMIN_USERNAME
          value: "admin"
        - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
          value: "admin"
        - name: SFTPGO_FTPD__BINDINGS__0__PORT
          value: "2121"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: sftp-data
        persistentVolumeClaim:
          claimName: sftp-data
      - name: config
        configMap:
          name: sftp-config
