version: '3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-storage:/var/lib/influxdb2

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data

volumes:
  uptime-kuma-data:
  grafana-storage:
  influxdb2-storage:
  portainer-data:
