kind: BGPConfiguration
apiVersion: projectcalico.org/v3
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  asNumber: 64512  
  serviceClusterIPs:
  - cidr: 10.43.0.0/16 
  serviceExternalIPs:
  - cidr: 192.168.49.0/24
