apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-config
data:
  sftpgo.json: |
    {
      "common": {
        "idle_timeout": 15,
        "upload_mode": 0,
        "actions": {
          "execute_on": [],
          "execute_sync": [],
          "hook": ""
        },
        "setstat_mode": 0,
        "temp_path": "",
        "proxy_protocol": 0,
        "proxy_allowed": [],
        "startup_hook": "",
        "post_connect_hook": "",
        "post_disconnect_hook": "",
        "data_retention_hook": "",
        "max_total_connections": 0,
        "max_per_host_connections": 20,
        "whitelist_file": "",
        "allow_self_connections": false
      },
      "sftpd": {
        "bindings": [
          {
            "port": 2022,
            "address": "",
            "apply_proxy_config": true
          }
        ],
        "max_auth_tries": 0,
        "banner": "",
        "host_keys": [
          "id_rsa",
          "id_ecdsa",
          "id_ed25519"
        ],
        "host_certificates": [],
        "host_key_algorithms": [],
        "moduli": [],
        "kex_algorithms": [],
        "ciphers": [],
        "macs": [],
        "trusted_user_ca_keys": [],
        "revoked_user_certs_file": "",
        "login_banner_file": "",
        "enabled_ssh_commands": [
          "md5sum",
          "sha1sum",
          "sha256sum",
          "cd",
          "pwd",
          "scp"
        ],
        "keyboard_interactive_authentication": true,
        "keyboard_interactive_auth_hook": "",
        "password_authentication": true,
        "folder_prefix": ""
      },
      "ftpd": {
        "bindings": [
          {
            "port": 2121,
            "address": "",
            "apply_proxy_config": true,
            "tls_mode": 2,
            "certificate_file": "",
            "certificate_key_file": "",
            "min_tls_version": 12,
            "force_passive_ip": "",
            "passive_ip_overrides": [],
            "client_auth_type": 0,
            "tls_cipher_suites": [],
            "passive_connections_security": 0,
            "active_connections_security": 0,
            "debug": false
          }
        ],
        "banner": "",
        "banner_file": "",
        "active_transfers_port_non_20": true,
        "passive_port_range": {
          "start": 50000,
          "end": 50100
        },
        "disable_active_mode": false,
        "enable_site": false,
        "hash_support": 0,
        "combine_support": 0,
        "certificate_file": "",
        "certificate_key_file": "",
        "ca_certificates": [],
        "ca_revocation_lists": []
      },
      "webdavd": {
        "bindings": [
          {
            "port": 10080,
            "address": "",
            "enable_https": false,
            "certificate_file": "",
            "certificate_key_file": "",
            "min_tls_version": 12,
            "client_auth_type": 0,
            "tls_cipher_suites": [],
            "prefix": "",
            "proxy_allowed": []
          }
        ],
        "certificate_file": "",
        "certificate_key_file": "",
        "ca_certificates": [],
        "ca_revocation_lists": [],
        "cors": {
          "enabled": false,
          "allowed_origins": [],
          "allowed_methods": [],
          "allowed_headers": [],
          "exposed_headers": [],
          "allow_credentials": false,
          "max_age": 0
        },
        "cache": {
          "users": {
            "expiration_time": 0,
            "max_size": 50
          },
          "mime_types": {
            "enabled": true,
            "max_size": 1000,
            "custom_mappings": []
          }
        }
      },
      "data_provider": {
        "driver": "sqlite",
        "name": "sftpgo.db",
        "host": "",
        "port": 0,
        "username": "",
        "password": "",
        "sslmode": 0,
        "connection_string": "",
        "sql_tables_prefix": "",
        "track_quota": 2,
        "delayed_quota_update": 0,
        "pool_size": 0,
        "users_base_dir": "",
        "actions": {
          "execute_on": [],
          "execute_for": [],
          "hook": ""
        },
        "external_auth_hook": "",
        "external_auth_scope": 0,
        "credentials_path": "",
        "pre_login_hook": "",
        "post_login_hook": "",
        "post_login_scope": 0,
        "check_password_hook": "",
        "check_password_scope": 0,
        "password_hashing": {
          "argon2_options": {
            "memory": 65536,
            "iterations": 1,
            "parallelism": 2
          },
          "bcrypt_options": {
            "cost": 10
          },
          "algo": "argon2id"
        },
        "password_validation": {
          "admins": {
            "min_entropy": 0
          },
          "users": {
            "min_entropy": 0
          }
        },
        "password_caching": true,
        "update_mode": 0,
        "prefer_database_credentials": false,
        "create_default_admin": true,
        "naming_rules": 0,
        "is_shared": 0,
        "users_base_dir_is_relative": false
      },
      "httpd": {
        "bindings": [
          {
            "port": 8080,
            "address": "",
            "enable_web_admin": true,
            "enable_web_client": true,
            "enable_rest_api": true,
            "enabled_login_methods": 0,
            "enable_https": false,
            "certificate_file": "",
            "certificate_key_file": "",
            "min_tls_version": 12,
            "client_auth_type": 0,
            "tls_cipher_suites": [],
            "proxy_allowed": [],
            "client_ip_proxy_header": "",
            "client_ip_header_depth": 0,
            "hide_login_url": 0,
            "render_openapi": true,
            "web_client_integrations": [],
            "oidc": {
              "client_id": "",
              "client_secret": "",
              "config_url": "",
              "redirect_base_url": "",
              "username_field": "",
              "scopes": [],
              "role_field": "",
              "custom_fields": [],
              "implicit_roles": false,
              "username_prefix": "",
              "session_duration": 0
            },
            "security": {
              "enabled": false,
              "allowed_hosts": [],
              "allowed_hosts_are_regex": false,
              "hosts_proxy_headers": [],
              "https_redirect": false,
              "https_host": "",
              "https_proxy_headers": [],
              "sts_seconds": 0,
              "sts_include_subdomains": false,
              "sts_preload": false,
              "content_type_nosniff": false,
              "content_security_policy": "",
              "permissions_policy": "",
              "cross_origin_opener_policy": "",
              "expect_ct_header": ""
            },
            "branding": {
              "web_admin": {
                "name": "",
                "short_name": "",
                "favicon_path": "",
                "logo_path": "",
                "login_image_path": "",
                "disclaimer_name": "",
                "disclaimer_path": "",
                "default_css": "",
                "extra_css": []
              },
              "web_client": {
                "name": "",
                "short_name": "",
                "favicon_path": "",
                "logo_path": "",
                "login_image_path": "",
                "disclaimer_name": "",
                "disclaimer_path": "",
                "default_css": "",
                "extra_css": []
              }
            },
            "setup_api_key": {
              "header": "",
              "key": ""
            }
          }
        ],
        "templates_path": "templates",
        "static_files_path": "static",
        "openapi_path": "openapi",
        "web_root": "",
        "certificate_file": "",
        "certificate_key_file": "",
        "ca_certificates": [],
        "ca_revocation_lists": [],
        "signing_passphrase": "",
        "token_validation": {
          "audience": [],
          "issuer": ""
        },
        "max_upload_file_size": 1048576000,
        "cors": {
          "enabled": false,
          "allowed_origins": [],
          "allowed_methods": [],
          "allowed_headers": [],
          "exposed_headers": [],
          "allow_credentials": false,
          "max_age": 0
        },
        "setup": {
          "installation_code": "",
          "installation_code_hint": ""
        }
      },
      "telemetry": {
        "bind_port": 0,
        "bind_address": "127.0.0.1",
        "enable_profiler": false,
        "auth_user_file": "",
        "certificate_file": "",
        "certificate_key_file": "",
        "min_tls_version": 12,
        "tls_cipher_suites": []
      },
      "kms": {
        "secrets": {
          "url": "",
          "master_key": "",
          "master_key_path": ""
        }
      },
            },
      "plugin": {
        "plugins": []
      },
      "mfa": {
        "totp": [
          {
            "name": "Default",
            "issuer": "SFTPGo",
            "algo": "sha1"
          }
        ]
      },
      "rate_limiters": [],
      "ldap": {
        "host": "",
        "port": 389,
        "proto": "ldap",
        "bind_dn": "",
        "bind_password": "",
        "base_dn": "",
        "search_filter": "(&(objectClass=posixAccount)(uid=%username%))",
        "search_base_dn": "",
        "attributes": {
          "username": "uid",
          "mail": "mail",
          "custom_one": "",
          "custom_two": ""
        },
        "start_tls": false,
        "insecure_skip_verify": true,
        "user_groups": [
          {
            "name": "ldapgroup1",
            "base_dn": "ou=Groups,dc=example,dc=org",
            "filter": "(&(objectClass=posixGroup)(memberUid=%username%))",
            "members_attr": "memberUID",
            "username_attr": "uid"
          }
        ]
      }
    }
    }
